name: lab2 autograding

on:
    pull_request:
        types: [labeled, synchronize, opened, reopened, ready_for_review]

jobs:
    build:
        if: contains(github.event.pull_request.labels.*.name, 'lab2')
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-22.04]
            fail-fast: false
        steps:
            - uses: actions/checkout@v1
              with:
                  fetch-depth: 1
            - name: dependency (ubuntu)
              run: |
                  curl -fsSL https://deb.nodesource.com/setup_21.x | sudo -E bash - &&\
                  sudo apt-get install -y nodejs
            - name: grading
              run: |
                  cd lab2
                  ./validate.sh
